version: '3.8'

services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000" # ホストの8000ポートをコンテナの8000ポートにマッピング
    volumes:
      - ./docker-dynamodb-data:/home/dynamodblocal/data # データを永続化するディレクトリ (ホスト側)
    working_dir: /home/dynamodblocal